// Generated by CoffeeScript 1.7.1
(function() {
  Number.prototype.clamp = function(min, max) {
    var inst, val;
    val = this.valueOf();
    inst = val;
    if (val < min) {
      inst = min;
    } else if (val > max) {
      inst = max;
    }
    return val;
  };

  String.prototype.endsWith = function(str) {
    return this.lastIndexOf(str) + str.length === this.length;
  };

  Object.defineProperty(Object.prototype, "stringify", {
    get: function() {
      return JSON.stringify(this);
    },
    enumerable: false
  });

}).call(this);
