// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    ERROR: {
      code: 422,
      msg: "API call to craftia error"
    },
    SUCCESS: {
      code: 200,
      msg: "API call to craftia success"
    }
  };

}).call(this);
